name = "InformationTheory"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Kraft"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

# Target for your main Kraft.lean file
[[lean_lib]]
name = "Kraft"

# Target for your InformationTheory/Coding folder
[[lean_lib]]
name = "InformationTheory"
